name: ExpertiseStylePlugin
version: '1.0-SNAPSHOT'
main: io.github.Gabriel.expertiseStylePlugin.ExpertiseStylePlugin
api-version: '1.21'
authors: [ Gabriel Nicolas ]
description: Plugin for my expertises and styles
depend:
  - DamagePlugin
  - NMLEnergySystem
commands:
  expertise:
    description: Opens the menu to choose your expertise
    usage: /<command>
  style:
    description: Opens the menu to choose your style
    usage: /<command>