name: ExpertiseStylePlugin
version: '1.0'
main: io.github.NoOne.expertiseStylePlugin.ExpertiseStylePlugin
api-version: '1.21'
depend:
  - DamagePlugin
  - NMLEnergySystem
  - NMLShields
commands:
  expertise:
    description: Opens the menu to choose your expertise
    usage: /<command>
  style:
    description: Opens the menu to choose your style
    usage: /<command>